<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div data-placeholder="messages"></div>
<script>
    require(['jquery'], function ($) {
        $(document).ready(function () {
            var errorMessages = $('.messages .message');
            $(window).ready(function(){
                setInterval(function(){ 
                    $('.page.messages .message').each(function(){ 
                    $(this).addClass('hidden')});
                }, 8000);
            });
        });
    });
</script>



