<div class="envios">
    <div>
        <div class="img">
            <img src="/static/frontend/Gloss/base/es_AR/images/retiro.png" alt="">
        </div>
        <p>
            <strong>Retiro en tienda GRATIS</strong><br>
            <a href="#">Consultar tu sucursal más cercana</a>
        </p>
    </div>
    <div>
        <div class="img">
            <img src="/static/frontend/Gloss/base/es_AR/images/envio.png" alt="">
        </div>
        <p><strong>Envíos GRATIS a Tucumán en compras superiores a $30.000. Envíos GRATIS a todo el país en compras superiores a $60.000.</strong></p>
    </div>
</div>