<?php
/**
 *
 */
?>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Página en Mantenimiento</title>
</head>
<style>
    html,body {
        height: 100%;
    }
    body {
        padding: 0;
        background-repeat: no-repeat;
        background-size: contain;
        background-position: center;
    }
    @media (max-width: 768px) {
        body {
            background-image: url('/errors/demo66/images/mobile-mant.jpg');
        }
    }
    @media (min-width: 769px) {
        body {
            background-image: url('/errors/demo66/images/desktop-mant.jpg');
        }
    }
</style>
