<?php
/**
 * @var $block \Ecommerce66\Brands\Block\Brand\Slider
 */
$brandOptionIds = $block->getSliderBrands();
if (!empty($brandOptionIds)):
    ?>
<div class="brand-slider-wrapper">
    <div class="title"><?= /* @noEscape */ __('Featured Brands') ?></div>
    <ul class="brand-list">
        <?php
        foreach ($brandOptionIds as $optionId):
            $brandDetails = $block->getBrandUrlDetails($optionId);
            if (!empty($brandDetails)):
                ?>
            <li class="brand-item">
                <a class="logo" href="<?= /* @noEscape */ $brandDetails['url'] ?>">
                    <img src="<?= /* @noEscape */ $brandDetails['logo'] ?>"
                         alt="<?= /* @noEscape */ $brandDetails['name'] ?>"/>
                </a>
            </li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
    <div class="clearfix"></div>
    <div class="action">
        <a href="<?= /* @noEscape */ $block->getBrandIndexUrl() ?>" class="action primary button">
            <?= /* @noEscape */ __('View More') ?>
        </a>
    </div>
    <script>
        require([
            'jquery',
            'slick'
        ], function ($) {
            jQuery(document).ready(function () {
                jQuery(".brand-slider-wrapper .brand-list").slick({
                    dots: false,
                    arrows: false,
                    infinite: true,
                    speed: 300,
                    autoplay: true,
                    slidesToShow: 4,
                    slidesToScroll: 1,
                    responsive: [
                        {
                            breakpoint: 992,
                            settings: {
                                slidesToShow: 3,
                                slidesToScroll: 1
                            }
                        },
                        {
                            breakpoint: 768,
                            settings: {
                                slidesToShow: 2,
                                slidesToScroll: 1
                            }
                        }
                    ]
                });
            });
        });
    </script>
</div>
<?php endif; ?>
