<div class="field <?= $block->escapeHtmlAttr($block->getAdditionalClasses()) ?>">
    <label class="label" for="<?= $block->getHtmlId() ?>">
        <span><?= $block->escapeHtml($block->getLabel()) ?></span>
    </label>
    <div class="control">
        <textarea type="text"
            id="<?= $block->getHtmlId() ?>"
            name="<?= $block->escapeHtmlAttr($block->getFieldName()) ?>"
            class="textarea <?= $block->getHtmlClass() ?>"><?= $block->escapeHtml($block->getValue()) ?></textarea>
    </div>
</div>
