<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Info $block */

/** @var \Magento\Wishlist\Model\Item $item */

$brandViewModel = $block->getData('brand_viewmodel');

$item = $block->getItem();
$product = $item->getProduct();
?>

<strong class="product brand product-item-brand">
    <?php
        $brandOptionId = $product->getBrand();
        $brandDetails = $brandViewModel->getBrandUrlDetailsViewModel($brandOptionId);
        if (!empty($brandDetails)):
        ?>
            <a class="product-item-link"
            href="<?= $escaper->escapeUrl($brandDetails['url']) ?>">
                <?=/* @noEscape */ $brandDetails['name'] ?>
            </a>
        <?php endif;
    ?>
</strong>

<strong class="product-item-name">
    <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" title="<?= $block->escapeHtmlAttr($product->getName()) ?>" class="product-item-link">
        <?= $block->escapeHtml($product->getName()) ?>
    </a>
</strong>


