<?php
// @ coding Standards IgnoreFile
/**
 * @var \Magento\Catalog\Block\Product\View\Details $block
 */
?>
<?php $helper = $this->helper(\Ecommerce66\ProductTabs\Helper\Data::class) ?>
<?php $tabCollection = $helper->getTabsCollection() ?>
<?php if ($tabCollection->getSize()): ?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php foreach ($tabCollection as $_tab): ?>
                <?php if (($_tab->getTabType() == 'attribute') || ($_tab->getTabType() == 'static')): ?>
                    <?php if (trim($_tab->getValue()) !=''): ?>
                        <?php if ($_tab->getTabType() == 'attribute'): ?>
                            <?php
                                $html = $block->getLayout()
                                    ->createBlock(Magento\Catalog\Block\Product\View\Description::class)
                                ->setAtCall($helper->convertAttributeToCallName($_tab->getValue()))
                                ->setAtCode($_tab->getValue())
                                ->setCssClass('description')
                                ->setAtLabel('none')
                                ->setAtType($helper->getAttributeType($_tab->getValue()))
                                ->setTitle($_tab->getTitle())
                                ->setTemplate('Ecommerce66_ProductTabs::product/view/attribute.phtml')
                                ->toHtml()
                            ?>
                        <?php else: ?>
                            <?php $html = $block->getLayout()
                                ->createBlock(Magento\Cms\Block\Block::class)
                                ->setBlockId($_tab->getValue())
                                ->toHtml() ?>
                        <?php endif ?>

                        <?php
                        if (!trim($html)) {
                            continue;
                        }
                            $alias = $_tab->getTabType().$_tab->getValue();
                            $label = $_tab->getTitle();
                        ?>

                        <div class="data item title"
                             aria-labeledby="tab-label-<?= /* @noEscape  */ $alias;?>-title"
                             data-role="collapsible" id="tab-label-<?= /* @noEscape  */ $alias;?>">
                            <a class="data switch"
                               tabindex="-1"
                               data-toggle="switch"
                               href="#<?= /* @noEscape  */ $alias; ?>"
                               id="tab-label-<?= /* @noEscape  */ $alias;?>-title">
                                <?= /* @noEscape  */ $label; ?>
                            </a>
                        </div>
                        <div class="data item content" id="<?= /* @noEscape  */ $alias; ?>" data-role="content">
                            <?= /* @noEscape  */ $html; ?>
                        </div>

                    <?php endif ?>
                <?php else: ?>
                    <?php
                        $html = $layout->renderElement($_tab->getTabType());
                    if (!trim($html)) {
                        continue;
                    }
                        $alias = $layout->getElementAlias($_tab->getTabType());

                        $label = __($_tab->getTitle());

                    if ($alias == 'reviews') {
                        $oldLabel = $block->getChildData($alias, 'title');
                        if (is_object($oldLabel)) {
                            $labelObject = (array)$oldLabel;
                            $countArray = end($labelObject);
                            if (isset($countArray[0])) {
                                $label = $label.' '.$countArray[0].'';
                            }
                        }
                    }
                    ?>
                    <div class="data item title"
                         aria-labeledby="tab-label-<?= /* @noEscape  */ $alias;?>-title"
                         data-role="collapsible" id="tab-label-<?= /* @noEscape  */ $alias;?>">
                        <a class="data switch"
                           tabindex="-1"
                           data-toggle="switch"
                           href="#<?= /* @noEscape  */ $alias; ?>"
                           id="tab-label-<?= /* @noEscape  */ $alias;?>-title">
                            <?= /* @noEscape  */ $label; ?>
                        </a>
                    </div>
                    <div class="data item content" id="<?= /* @noEscape  */ $alias; ?>" data-role="content">
                        <?= /* @noEscape  */ $html; ?>
                    </div>
                <?php endif ?>
            <?php endforeach ?>
        </div>
    </div>
<?php endif ?>
