user                    www-data;
worker_processes        auto;
pid                     /var/run/nginx.pid;

events {
    # max clients = worker_connections * worker_processes
    worker_connections  1024;
    # optimized to serve many clients with each thread, essential for linux -- for testing environment
    use epoll;
    # Workflows will accept all connections
    multi_accept on;
    # Workflows will take turns Connection
    accept_mutex on;
}

http {
    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    log_format          main  '$remote_addr - $remote_user [$time_local] "$request" '
                              '$status $body_bytes_sent "$http_referer" '
                              '"$http_user_agent" "$http_x_forwarded_for" '
                              '$request_time';

    access_log          /dev/stdout main buffer=16k;
    error_log           /dev/stderr warn;

    # can boost performance, but you need to test those values
    open_file_cache max=10240 inactive=20s;
    open_file_cache_valid 60s;
    open_file_cache_min_uses 2;
    open_file_cache_errors on;

    sendfile            on;
    keepalive_timeout   75;

    # send headers in one piece, it is better than sending them one by one
    tcp_nopush on;
    # don't buffer data sent, good for small data bursts in real time
    tcp_nodelay on;

    server_tokens 	off;

    # Define la zona y la tasa limite de requests
    limit_req_zone $binary_remote_addr zone=search_rate:10m rate=1r/s;

    # Incluye el archivo globalblacklist.conf
    include /etc/nginx/conf.d/globalblacklist.conf;

    # Incluye la configuración de botblocker
    include /etc/nginx/bots.d/botblocker-nginx-settings.conf;

    include /etc/nginx/sites-enabled/*;
}
