<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Ceb\Gtm\ViewModel\ProductList $viewModel */
$viewModel = $block->getViewModel();

$items = $viewModel->getFirstVisibleItems(10);
?>

<?php if (!empty($items)): ?>
    <script>
        window.dataLayer = window.dataLayer || [];
        window.dataLayer.push({
            event: 'view_item_list',
            ecommerce: {
                items: <?= /* @noEscape */ json_encode($items, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP) ?>
            }
        });
    </script>
    <script type="text/x-magento-init">
    {
        "*": {
            "Ceb_Gtm/js/datalayer": {
                "store_currency": "<?= $block->escapeJs($viewModel->getStoreCurrencyCode()) ?>"
            }
        }
    }
    </script>
<?php endif; ?>
