<?php
/** @var $block \Ecommerce66\CartQuantity\Block\Product\CustomQty */
$product = $block->getProduct();
?>
<?php if ($product && $product->isSaleable()): ?>
    <div class="qty-field-wrapper qty-<?= $block->escapeJs($product->getId()) ?>" data-product="<?= $block->escapeJs($product->getId()) ?>" data-mage-init='{"customQty": {"pid": "<?= $block->escapeJs($product->getId()) ?>"}}'>

        <span>
              <button type="button" id="1-dec" class="decreaseQty">
              <i class="fas fa-minus"></i></button>
          </span>
        <input id="cart-<?= $block->escapeJs($product->getId()) ?>-qty"
               name="qty"
               data-cart-item-id="1"
               value="1"
               type="number"
               size="4"
               step="1"
               min="1"
               max="9999"
               title="<?= $block->escapeJs($product->getId()) ?>"
               class="input-text qty"
               data-validate="{required:true,'validate-greater-than-zero':true}"
               data-role="cart-item-qty"/>

        <span>
            <button type="button" id="1-upt" class="increaseQty"><i class="fas fa-plus"></i></button>
        </span>
    </div>
<?php endif; ?>
