<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Ceb\Gtm\ViewModel\GtmData $vm */
$vm = $block->getViewModel();
$measurementId = $vm->getMeasurementId();
if (!$measurementId) {
    return;
}
?>
<script type="text/x-magento-init">
{
    "*": {
        "gaCapture": {
            "measurementId": <?= /* @noEscape */ json_encode($measurementId, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP) ?>
        }
    }
}
</script>
