<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Ceb\ViewModelCustom\ViewModel\CebSummary $viewModel */
$viewModel = $block->getData('view_model');
$summary = $viewModel->getSummary();
?>
<div class="ceb-summary" data-bind="scope: 'cebSummary'">
    <strong><?= $block->escapeHtml($summary['title']) ?></strong>
    <span><?= $block->escapeHtml($summary['lazy_report']) ?></span>
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
{
    ".ceb-architecture-summary": {
        "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
    }
}
</script>
